package com.frcteam1939.powerup2018.util;

public enum AutonomousOptions {
	CENTER, LEFT_PRIORITIZE_SWITCH, LEFT_PRIORITIZE_SCALE, RIGHT_PRIORITIZE_SWITCH, RIGHT_PRIORITIZE_SCALE, DO_NOTHING, CROSS_AUTO_LINE
}
